var mongoose = require('mongoose');

var HistoryMachineSchema = new mongoose.Schema({
  NameMachine:{type: String},
  Model:{type: String},
  Voltage:{type: String},
  PowerFactor:{type: String},
  Head:{type: String},
  CodeMachine:{type: String},
  Pole:{type: String},
  Current:{type: String},
  Frequency:{type: String},
  Location:{type: String},
  Phase:{type: String},
  RPM:{type: String},
  uF:{type: String},
  OilSealNo:{type: String},
  Brand:{type: String},
  Power:{type: String},
  IP:{type: String},
  MechSealNo:{type: String},
  DateSetup:{type: String},
  Date:{type: String},
  Time:{type: String},
  JobNo:{type: String},
  Category:{type: String},
  Cause:{type: String},
  Detail:{type: String},
  Spare:{type: String},
  Quantity:{type: String},
  Operator:{type: String},
  Recorder:{type: String},
  Informer:{type: String},
  Faction:{type: String},
  Department:{type: String},
  DateRepair:{type: String},
  TimeRepair:{type: String},
  DateStartRepair:{type: Date},
  TimeStartRepair:{type: String},
  DateFinishRepair:{type: String},
  TimeFinishRepair:{type: String},
  updated_at: { type: Date, default: Date.now },
  });
module.exports = mongoose.model('HistoryMachine', HistoryMachineSchema)